services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: 'no'
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: /bin/sh -c "cd /app; bun install && bun run dev"

  db:
    image: postgres:16-alpine
    restart: 'no'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
