export async function getUsers({ request, response }) {
  // Implement your logic to retrieve users
  // For demonstration, we'll return a static array of users

  return [
    { id: 1, name: 'John Doe' },
    { id: 2, name: 'Jane Doe' },
  ];
}

export async function createUser({ request, response }) {
  // Parse the request body to get user data
  const userData = await request.json();

  // Implement your logic to create a new user
  // For demonstration, we'll simulate creating a user and returning it
  const newUser = {
    id: 3, // In a real application, this would be generated by the database
    name: userData.name,
  };

  // Return the newly created user
  return newUser;
}
